CREATE TABLE Item (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

-- Create Author Table
CREATE TABLE authors (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(20),
    last_name VARCHAR(20),
    FOREIGN KEY (item_id) REFERENCES Item(id)
  );

CREATE INDEX idx_authors_item_id ON authors(item_id);


-- Create Game Table
CREATE TABLE games (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archived BOOLEAN,
    multiplayer BOOLEAN,
    last_played_at DATE,
    author_id INT,
    FOREIGN KEY (item_id) REFERENCES Item(id)
  );

  CREATE INDEX idx_games_item_id ON games(item_id);